### ISSUE TITLE
CamelCase for acronym typenames?

### ISSUE THREAD

**Issue by lo48576** [kornelski/rust-rgb#25]
Rust's [RFC 0430 about naming conventions](https://github.com/rust-lang/rfcs/blob/master/text/0430-finalizing-naming-conventions.md#fine-points) says:

> In `CamelCase`, acronyms count as one word: use `Uuid` rather than `UUID`.

For consistency among other codes, I think `RGB` and `RGBA` should be `Rgb` and `Rgba`.
(`RGBA` looks like a constant rather than a type.)

What do you think?

**Comment by kornelski** [comment]
I have conflicted feelings about this.

On one hand, it'd be nice to follow an official recommendation. OTOH that looks weird to me. In non-Rust languages it's `RGB` or `rgb`, but I don't remember ever seeing `Rgb`.

**Comment by ripytide** [comment]
I think same-language conventions have greater value for code readability than across-language conventions. As such I am in favor of this change.

**Comment by ripytide** [comment]
Also worth adding the `RGB8` -> `RgbU8` suggestion from #62 here for visibility.

**Comment by kornelski** [comment]
Yeah, I'm not sure about this. `RGB` is a super-common acronym, and the `Rgb` spelling is mostly a Rust convention, and it looks odd to me especially when not part of a `CamelCase` name. `RGB8` is widely recognized in the industry, and `RgbU8` is a Rusty neologism.
So I'm torn between being consistent with Rust vs consistent with pretty much everything except Rust.

It is possible to support both, by re-exporting the other with `#[doc(hidden)]`, but one of them needs to be chosen as the canonical. I'm still leaning towards `RGB` and `RGB8`.

**Comment by ripytide** [comment]
> RGB is a super-common acronym

`HTML`, `CSS`, `HTTP` are all commonly-known acronyms, but crates that implement their types all use the rust naming conventions for types using them such as [Http](https://docs.rs/hyper/latest/hyper/rt/bounds/trait.Http2ServerConnExec.html#) in `hyper`, [Css](https://docs.rs/cssparser/latest/cssparser/struct.CssStringWriter.html) in `cssparser`, and [Html](https://docs.rs/html/latest/html/root/struct.Html.html) in `html`. To break this language convention is the greater surprise in my opinion.

[The principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) seems relevant here.

Since you are split fairly evenly between the two options can I suggest we default to `Rgb` since that is likely to be more familiar to the target-audience of this library (rust-developers) as opposed to the greater industry?

**Comment by kornelski** [comment]
OK, that makes sense
