### ISSUE TITLE
Is it possible to make basic ops const-fn?

### ISSUE THREAD

**Issue by Boscop** [kornelski/rust-rgb#9]
Is it possible to make basic ops const-fn? E.g. `fn mul(self, r: T) -> Self::Output`.

To allow them to be used in constant initializations (without incurring the overhead of lazy_static).

**Comment by kornelski** [comment]
I think `const fn` isn't stable yet? Other than that I think it should be possible to do for most functions.

**Comment by owenthewizard** [comment]
It's not stable now?

**Comment by kornelski** [comment]
Yup, it's stable and good to go!

**Comment by ripytide** [comment]
While I understand that `const fn` is now stable, `const fn in trait` is not yet stable so the example provided of `fn mul(self, r: T) -> Self::Output` is (at the time of writing) not yet able to become `const fn mul(self, r: T) -> Self::Output` since it belongs to the trait `Mul`. Currently, the only `const fn` methods I can see in this crate are the `new() -> Self` methods, but as changes from `not_const` to `const` on inherent methods is backwards compatible I don't see this as high priority for #64.

**Comment by kornelski** [comment]
I was initially thinking about just inherent functions. The `std::ops` is unlikely to be const in the foreseeable future.
